apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiter-service
  labels:
    app: waiter-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: waiter-service
  template:
    metadata:
      labels:
        app: waiter-service
    spec:
      containers:
      - name: waiter-service
        image: waiter-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /root/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: waiter-service-config