{
 "title": "JMeter + Loki + Tempo",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JMeter_sample",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$JMeter_sample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "JMeter_sample" },
  {
   "title": "$JMeter_sample throughput over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"jmeter\", label=~\"$JMeter_sample\"} [1s]))",
     "legendFormat": "{{label}} avg TPS"
    },
    {
     "expr": "sum by(label) (count_over_time({job=\"jmeter\", label=~\"$JMeter_sample\", success=\"0\"} [1s]))",
     "legendFormat": "error TPS"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{label=\"$JMeter_sample\"} | json | unpack"
    }
   ]
  },
  {
   "title": "$JMeter_sample Average stats over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(avg_over_time({job=\"jmeter\", label=\"$JMeter_sample\"} | json responseTime=\"responseTime\" | unwrap responseTime [$__auto]))",
     "legendFormat": "Response Time"
    },
    {
     "expr": "avg(avg_over_time({job=\"jmeter\", label=\"$JMeter_sample\"} | json connectTime=\"connect_time\" | unwrap connectTime [$__auto]))",
     "legendFormat": "Connect Time"
    },
    {
     "expr": "avg(avg_over_time({job=\"jmeter\", label=\"$JMeter_sample\"} | json latency=\"latency\" | unwrap latency [$__auto]))",
     "legendFormat": "latency"
    },
    {
     "dataset": "JMeter",
     "rawSql": "SELECT slaThreshold as SLA, $__timeFrom()  as Time FROM JMeter.SLAThresholds where transactionType like $JMeter_sample\nunion\nSELECT slaThreshold as SLA, $__timeTo() as Time FROM JMeter.SLAThresholds where transactionType like $JMeter_sample"
    }
   ]
  },
  {
   "title": "Tempo Traces",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "filters": [
      { "id": "069f58db", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": "$JMeter_sample",
       "valueType": "string"
      }
     ],
     "groupBy": [
      { "id": "ec9af292", "scope": "span", "tag": "" }
     ],
     "limit": 20,
     "serviceMapQuery": "{service=\"definitely-not-jmeter\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{label=\"$JMeter_sample\", success=\"0\"} | json responseCode=\"responseCode\", responseMessage=\"responseMessage\" | unpack"
    }
   ]
  }
 ]
}