{
 "title": "JMeter + Loki",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(label) (count_over_time({job=\"jmeter\", success=\"0\"} [1s]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Average Response Times over time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"jmeter\"} | json responseTime=\"responseTime\" | unwrap responseTime [$__auto]) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Throughput Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by(label) (count_over_time({job=\"jmeter\"} [1s]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Error details",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(label, responseCode) (count_over_time({job=\"jmeter\", success=\"0\"} [$__auto]))",
     "legendFormat": "error count"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "max by(threadGroup) (max_over_time({job=\"jmeter\"} | json | unwrap grpThreads [$__auto]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by(label) (max_over_time({job=\"jmeter\"} | json responseTime | unwrap responseTime [$__auto]))"
    },
    {
     "expr": "avg by(label) (avg_over_time({job=\"jmeter\"} | json responseTime=\"responseTime\" | unwrap responseTime [$__auto]))",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "min by(label) (min_over_time({job=\"jmeter\"} | json responseTime=\"responseTime\" | unwrap responseTime [$__auto]))",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sum by(label) (count_over_time({job=\"jmeter\"} | json responseTime [$__auto]))"
    },
    {
     "expr": "sum by(label) (count_over_time({job=\"jmeter\", success=\"0\"} [$__auto]))"
    }
   ]
  }
 ]
}