{
 "title": "JMeter + Loki",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(threadGroup_extracted) (max_over_time({job=\"jmeter\"} | json | regexp `\\\"threadGroup\\\" : \\\"(?P<threadGroup>.*)\\s*\\d*-\\d*` | unwrap grpThreads [$__auto]))"
    }
   ]
  },
  {
   "title": "Throughput Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by(label) (count_over_time({job=\"jmeter\"} [1s]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Average Response Times over time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time({job=\"jmeter\"} | json responseTime=\"responseTime\" | unwrap responseTime [$__auto]) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Errors Over Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count by(responseCode) (rate({job=\"jmeter\", success=\"0\"} | json [$__auto]))",
     "legendFormat": "error count"
    }
   ]
  },
  {
   "title": "Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(label) (count_over_time({job=\"jmeter\", success=\"0\"} [$__auto]))",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}