server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: jmeter_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jmeter
          __path__: /var/logs/*.jtl
    pipeline_stages:
          - json:
              expressions:
                success: success
                label: label
                latency: latency
                connect_time: connect_time
                responseTime: responseTime
                receivedBytes: receivedBytes
                responseSize: responseSize
                responseCode: responseCode
                startTime: startTime
                threadGroup: threadGroup
                grpThreads: grpThreads
                threadCount: threadCount
                traceID: traceID
                responseMessage: responseMessage
          - regex:
              expression: "^(?P<threadGroup>.*)\\s*\\d+-\\d+"
              source:     "threadGroup"
          - timestamp:
              source: startTime
              format: UnixMs
          - labels:
              label:
              responseCode:
              success:
              threadGroup: